export const APP_VERSION = '2025.12.15.35'
export const ASSET_VERSION = '20251215-35'

export const STORAGE_KEYS = {
  theme: 'xuantian.theme',
  perfMode: 'xuantian.perf.mode.v1',
  notes: 'xuantian.notes.v1',
  notesMeta: 'xuantian.notesMeta.v1',
  notesView: 'xuantian.notes.view.v1',
  notesTocFold: 'xuantian.notes.toc.fold.v1',
  tagFilter: 'xuantian.chronicles.tag',
  treasureOrder: 'xuantian.treasures.order.v1',
  bookmarks: 'xuantian.bookmarks.v1',
  readingLast: 'xuantian.reading.last.v1',
  readingImmersive: 'xuantian.reading.immersive.v1',
  grottoSelected: 'xuantian.grotto.selected.v1',
  grottoLayer: 'xuantian.grotto.layer.v1',
  grottoTone: 'xuantian.grotto.tone.v1',
  grottoAnnotations: 'xuantian.grotto.annotations.v1',
  relationsSelected: 'xuantian.relations.selected.v1',
  relationsKind: 'xuantian.relations.kind.v1',
  relationsOnly: 'xuantian.relations.only.v1',
  relationsAnnotations: 'xuantian.relations.annotations.v1',
  annotationsHallSource: 'xuantian.annotations.hall.source.v1',
  annotationsHallTone: 'xuantian.annotations.hall.tone.v1',
  annotationsHallLayer: 'xuantian.annotations.hall.layer.v1',
  annotationsHallKind: 'xuantian.annotations.hall.kind.v1',
  annotationsHallUndo: 'xuantian.annotations.hall.undo.v1',
  annotationsHallBackup: 'xuantian.annotations.hall.backup.v1',
  notesImportHint: 'xuantian.notes.importHint.v1',
  findOptions: 'xuantian.find.options.v1',
} as const
